/**
 * The sheet that goes next to the fragments: what to paste, in what order, and
 * what has not been verified yet.
 *
 * Written as a sibling file rather than as a comment inside a fragment. A note
 * to the person pasting does not belong in the body a student reads, and an
 * HTML comment in a Document is one editor change away from being visible.
 *
 * Run: node scripts/blackboard/notes.mjs
 */
import { writeFile } from 'node:fs/promises';

import {
  ASSET_BASE,
  REVEAL,
  WIDGET_DEPLOYED,
  WIDGET_FRAME_PX,
} from './components.mjs';
import { RENDER } from './math.mjs';

const target = new URL(
  '../../../blackboard_content/math_a251_week4/WEEK4_BB_PASTE_NOTES.txt',
  import.meta.url,
);

const rule = '='.repeat(78);

const notes = `MATH A251 WEEK 4 - BLACKBOARD PASTE NOTES
${rule}

Generated by math251/scripts/export-blackboard.mjs. Do not hand-edit the
fragments; edit content/week4/*.mdx and re-run \`npm run export:bb\`.

WHAT CHANGED, AND WHY
${'-'.repeat(78)}
The first attempt put each of these three pages behind a 720px frame. That was
rejected on sight: they are the week's assigned reading, and a reading behind a
frame is a porthole with a scrollbar inside a page that already scrolls, and a
blank rectangle whenever the network or the deploy is a moment behind.

So the reading is now native Blackboard content. Each __BB.html file is the
BODY of a Document: select all, paste into the Ultra Document editor, save. No
script, no stylesheet, no class names, no viewport units, nothing root-relative.
Only the interactive graph keeps a frame, and it sits inside the 1.7 reading at
the point where the corner is discussed.

TWO OUTPUTS PER SECTION. YOU PICK.
${'-'.repeat(78)}
  <slug>__BB.html      The reading, pasted in as native Blackboard content.
                       Full width, no nested scroll, nothing to load.
  <slug>__IFRAME.html  A navy bar carrying a full-screen link, then a 720px
                       frame. Nothing else.

Both are correct and neither replaces the other. The fragment is what the
reversal of 2026-09-12 was about, and it is the one that does not depend on a
deploy. The frame keeps the page and the Document in step automatically, which
is worth something while a page is still being edited. Each file holds only its
own block, so either one is open, select all, copy.

WHAT THE FRAME NOW POINTS AT
${'-'.repeat(78)}
The frame used to point at the full-screen page, and inside a Document that
read as a foreign object: a dark, site-chrome'd page floating in Blackboard's
white shell, under a blurb that repeated the page's own opening, over a caption
explaining how an iframe works, with the title showing three times.

The page inside the frame is now a presentation built for the frame:

  ${ASSET_BASE}/bb/<slug>/      what the frame shows
  ${ASSET_BASE}/embed/<slug>/   what the bar links to

Same words, same MDX file, three presentations. The /bb/ page is light, full
frame width, and carries no masthead, no footer and no h1, because the Document
title already says the title. The blurb and the caption paragraphs are gone.

PASTE ORDER
${'-'.repeat(78)}
  1.  section-1-7      Limits, Continuity, and Differentiability (Section 1.7)
  2.  ivt-openstax     Continuity and the Intermediate Value Theorem (OpenStax supplement)
  3.  section-1-8      The Tangent Line Approximation (Section 1.8)

The overview students already have sends them to the supplement straight after
1.7, so that is the order the Documents go in.

DO THIS FIRST: THE PASTE TEST
${'-'.repeat(78)}
MATH_A251_PASTE_TEST__BB.html has NOT been run. It carries the four constructs
everything else rests on, each with a line saying what it should look like.
Paste it into a THROWAWAY Document, save it, close it, reopen it, then delete
the Document. It takes about two minutes and it answers a question no browser
can: whether the editor's sanitiser keeps what was pasted.

  Check 1-3  MathML.       If stripped: set RENDER = "svg" in
                           math251/scripts/blackboard/math.mjs and re-run
                           \`npm run export:bb\`. Every expression becomes
                           self-contained inline SVG instead. The fallback has
                           been rendered and checked; it works, it is just about
                           four times the bytes.
  Check 4    <details>.    If stripped: set REVEAL = "visible" in
                           math251/scripts/blackboard/components.mjs and re-run.
                           Every question then renders above its own answer.
  Check 5-6  <iframe>.     If stripped, the Desmos graphs on 1.8 and the graph
                           inside 1.7 cannot be embedded and become links.

Current settings: RENDER = ${RENDER}, REVEAL = ${REVEAL}.

${
  WIDGET_DEPLOYED
    ? ''
    : `DO THIS SECOND: THE GRAPH IS NOT DEPLOYED
${'-'.repeat(78)}
The 1.7 fragment contains a ${WIDGET_FRAME_PX}px frame pointing at

  ${ASSET_BASE}/widget/corner-slopes/

Nothing has been committed, pushed or deployed, so that URL is a 404 today and
the frame will render as an empty box in the middle of the reading. Open the URL
yourself before pasting 1.7. Once the Pages workflow has run for a commit that
contains app/widget/corner-slopes/, set WIDGET_DEPLOYED = true in
math251/scripts/blackboard/components.mjs and re-run the exporter.

The reading does not depend on it. The line and the link above the frame say
what the graph is for, so a student who never loads it still has the sentence.

`
}DO THIS BEFORE PASTING EITHER 1.7 OR 1.8: PUSH THE THUMBNAILS
${'-'.repeat(78)}
Each video block now carries a thumbnail card. The image is SELF-HOSTED, not
hotlinked from i.ytimg.com, so that a Document does not make every page view a
request to Google. The two files are

  math251/public/media/video/cSXE_QpiWrY.jpg   640x360, 19 KB
  math251/public/media/video/X0qVfMokn84.jpg   640x360, 23 KB

and the fragments reference them at

  ${ASSET_BASE}/media/video/<id>.jpg

Checked 2026-09-12: both of those URLs return 404. They are in the working copy
and in dist/client, but nothing has been committed or pushed, so until the Pages
workflow runs for a commit containing them a pasted fragment shows a broken
image where the thumbnail should be. The rest of the block still reads: the
title, the duration, the caption caveat and the link are all text.

WHAT IS IN EACH FILE
${'-'.repeat(78)}
Every word of the reading is in the Document. The full-screen route still
exists and each fragment ends with a link to it, but only as a convenience for
someone who would rather read the page on its own. It is never the way to the
content.

Both videos are links rather than players. Neither has a caption track that is
not auto-generated, which is recorded per video id in math251/docs/
video-reviews.json. Each link keeps its running time and the line saying you can
read the page instead of watching.

Two edits were made to the wording, both agreed: the weekday in "What to be able
to do by Friday" is gone, and so are the three pointers at Applied Assignment 1.
Dates and assignments live in the LMS; this content is generated from a public
repository. The exporter fails the build if either comes back.

IFRAME HEIGHTS
${'-'.repeat(78)}
  section-1-8   Desmos, ln(x) and its tangent line        420px
  section-1-8   Desmos, choose your own function          420px
  section-1-7   Slopes at a corner (course widget)        ${String(WIDGET_FRAME_PX).padStart(3)}px
  __IFRAME.html /bb/<slug>/ in a panel                    720px

The thumbnail card is 482 x 382 px at a 1100px column and 278 x 318 px at a
390px one: the image carries width and height attributes so Blackboard reserves
the space, plus max-width so a phone column shrinks it rather than overflowing.

The widget frame is its tallest measured state plus 40. Every slider position
was swept against every gap setting at thirteen widths from 280px to 1026px:
the widget is between 573px and 621px tall across all of them, so nothing
scrolls inside the frame at any width a Blackboard column can be.

Note the width the frame actually gets. At a 390px phone the Document's own
padding leaves the frame about 316px wide, not 390px, which is why the sweep
goes down to 280px.

${rule}
`;

await writeFile(target, notes, 'utf8');
console.log(`wrote ${target.pathname.split('/').pop()}`);
